name = "backend"
compatibility_date = "2024-08-08"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"



[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjY0NTk4OGMtMjQ4My00YTUxLWI0ZTgtOGVhN2Q4MmFkNTJmIiwidGVuYW50X2lkIjoiODZlMzZhZGUyMjhjZWU1YzhkMDA3ZmNlOGZiZmQ4OGU0MmRiNzU4MmYzZDNmYWU3M2NiNzVmOWU2ZjU1OTNjNyIsImludGVybmFsX3NlY3JldCI6ImE2MTgzOWM5LWQ4NWMtNGIyNi1hMGY2LWMxZjE5Y2JjZGNmMSJ9.1L4VBOk6vISTpZn4sK6xXNRjeUC_tCkJMGMKEEcYRxY"
JWT_SECRET= "SHREYASHISHKOSTI"
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"